### PR TITLE
update VS version

### PR DESCRIPTION
**Pull request by PatrickFarley**
The sample works in VS2017

### CODE REVIEW

**Comment by PatrickFarley** [comment]
@oliverwm Please merge this PR

**Comment by PatrickFarley** [comment]
@lydia-gu , @cthrash : Are you able to merge? Who owns this repo?

**Comment by cthrash** [comment]
I feel like the document should indicate the oldest Visual Studio that is supported, with the assumption that newer versions provide proper backward-compat support.  If I saw that doc saying to use VS 2017, I wouldn't assume VS 2015 is supported.  This is particularly true when there isn't a C runtime dependency, which is generally updated along with VS itself.  WDYT?

**Comment by PatrickFarley** [comment]
@cthrash, That's a fair point, but our policy on the docs team is to always assume the latest version (of VS, Windows, etc.) because we want to encourage developers to use the up-to-date versions anyway.

**Comment by cthrash** [comment]
Even if the [solution](https://github.com/Microsoft/Cognitive-Samples-VideoFrameAnalysis/blob/0390ce594ff998afacff16c3bc36429220d5ead2/Windows/VideoFrameAnalysis.sln#L3) file states otherwise?

**Comment by PatrickFarley** [comment]
Yes. But technically Readme files are not the docs, so you may have a different rule. This PR is old and I don't remember who originally requested the change, so you can close it if you wish.

**Pull request closed without merging**
